alter table services
add column price_effective_from timestamptz not null default current_timestamp;

create table service_price_history (
  id bigint generated by default as identity primary key,
  service_id bigint not null references services (id) on delete cascade,
  old_price numeric(18, 2) not null check (old_price > 0),
  effective_from timestamptz not null,
  effective_to timestamptz not null,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint chk_service_price_history_period check (effective_to >= effective_from)
);

create index idx_service_price_history_service_id
    on service_price_history (service_id, effective_to desc);
