-- V1 creates the full relational foundation planned for milestone 0.
-- Table names intentionally stay close to the Vietnamese business terminology in the project plan.

create table loaisanh (
  id bigint generated by default as identity primary key,
  ten_loai_sanh varchar(100) not null,
  don_gia_ban_toi_thieu numeric(18, 2) not null check (don_gia_ban_toi_thieu > 0),
  mo_ta text,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint uq_loaisanh_ten unique (ten_loai_sanh)
);

create table sanh (
  id bigint generated by default as identity primary key,
  loaisanh_id bigint not null references loaisanh (id),
  ten_sanh varchar(150) not null,
  suc_chua_toi_da integer not null check (suc_chua_toi_da > 0),
  don_gia_ban numeric(18, 2) not null check (don_gia_ban > 0),
  trang_thai varchar(20) not null default 'TRONG' check (trang_thai in ('TRONG', 'DANG_DUNG', 'BAO_TRI')),
  mo_ta text,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint uq_sanh_ten unique (ten_sanh)
);

create index idx_sanh_loaisanh_id on sanh (loaisanh_id);

create table ca (
  id bigint generated by default as identity primary key,
  ten_ca varchar(100) not null,
  gio_bat_dau time not null,
  gio_ket_thuc time not null,
  mo_ta text,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint uq_ca_ten unique (ten_ca),
  constraint chk_ca_khung_gio check (gio_ket_thuc > gio_bat_dau)
);

create table monan (
  id bigint generated by default as identity primary key,
  ten_mon_an varchar(150) not null,
  loai_mon varchar(100) not null,
  don_gia_hien_tai numeric(18, 2) not null check (don_gia_hien_tai > 0),
  trang_thai varchar(10) not null default 'CON' check (trang_thai in ('CON', 'HET')),
  mo_ta text,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint uq_monan_ten unique (ten_mon_an)
);

create index idx_monan_trang_thai on monan (trang_thai);

create table dichvu (
  id bigint generated by default as identity primary key,
  ten_dich_vu varchar(150) not null,
  loai_dich_vu varchar(100) not null,
  don_vi_tinh varchar(50) not null,
  don_gia_hien_tai numeric(18, 2) not null check (don_gia_hien_tai > 0),
  trang_thai varchar(20) not null default 'HOAT_DONG' check (trang_thai in ('HOAT_DONG', 'NGUNG_HOAT_DONG')),
  mo_ta text,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint uq_dichvu_ten unique (ten_dich_vu)
);

create index idx_dichvu_trang_thai on dichvu (trang_thai);

create table chucnang (
  id bigint generated by default as identity primary key,
  ma_chuc_nang varchar(100) not null,
  ten_chuc_nang varchar(150) not null,
  module_key varchar(100) not null,
  mo_ta text,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint uq_chucnang_ma unique (ma_chuc_nang)
);

create table nhomnguoidung (
  id bigint generated by default as identity primary key,
  ten_nhom varchar(100) not null,
  mo_ta text,
  la_nhom_he_thong boolean not null default false,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint uq_nhomnguoidung_ten unique (ten_nhom)
);

create table nguoidung (
  id bigint generated by default as identity primary key,
  nhomnguoidung_id bigint not null references nhomnguoidung (id),
  ten_dang_nhap varchar(100) not null,
  mat_khau_hash varchar(255) not null,
  ho_ten varchar(150) not null,
  email varchar(255),
  so_dien_thoai varchar(20),
  trang_thai varchar(20) not null default 'ACTIVE' check (trang_thai in ('ACTIVE', 'INACTIVE', 'LOCKED')),
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint uq_nguoidung_ten_dang_nhap unique (ten_dang_nhap),
  constraint uq_nguoidung_email unique (email),
  constraint uq_nguoidung_so_dien_thoai unique (so_dien_thoai)
);

create index idx_nguoidung_nhomnguoidung_id on nguoidung (nhomnguoidung_id);

create table bangphanquyen (
  nhomnguoidung_id bigint not null references nhomnguoidung (id) on delete cascade,
  chucnang_id bigint not null references chucnang (id) on delete cascade,
  created_at timestamptz not null default current_timestamp,
  primary key (nhomnguoidung_id, chucnang_id)
);

create table thamso (
  id smallint primary key,
  ti_le_coc_toi_thieu numeric(5, 2) not null check (ti_le_coc_toi_thieu > 0 and ti_le_coc_toi_thieu <= 100),
  phat_tre_enabled boolean not null default true,
  ti_le_phat_tre numeric(5, 2) not null check (ti_le_phat_tre >= 0 and ti_le_phat_tre <= 100),
  so_ngay_huy integer not null check (so_ngay_huy > 0),
  ti_le_hoan_coc numeric(5, 2) not null check (ti_le_hoan_coc >= 0 and ti_le_hoan_coc <= 100),
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint chk_thamso_singleton check (id = 1)
);

create table tieccuoi (
  id bigint generated by default as identity primary key,
  sanh_id bigint not null references sanh (id),
  ca_id bigint not null references ca (id),
  ten_chu_re varchar(150) not null,
  ten_co_dau varchar(150) not null,
  so_dien_thoai_chu_re varchar(20),
  so_dien_thoai_co_dau varchar(20) not null,
  ngay_dat_tiec date not null default current_date,
  ngay_dai_tiec date not null,
  so_luong_ban integer not null check (so_luong_ban > 0),
  so_ban_du_tru integer not null default 0 check (so_ban_du_tru >= 0),
  don_gia_ban numeric(18, 2) not null check (don_gia_ban > 0),
  trang_thai varchar(20) not null default 'CHO_XAC_NHAN' check (
    trang_thai in ('CHO_XAC_NHAN', 'DA_XAC_NHAN', 'DANG_DIEN_RA', 'DA_THANH_TOAN', 'DA_HUY')
  ),
  ghi_chu text,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint chk_tieccuoi_ngay_hop_le check (ngay_dai_tiec >= ngay_dat_tiec)
);

create index idx_tieccuoi_sanh_id on tieccuoi (sanh_id);
create index idx_tieccuoi_ca_id on tieccuoi (ca_id);
create index idx_tieccuoi_ngay_dai_tiec on tieccuoi (ngay_dai_tiec);
create index idx_tieccuoi_trang_thai on tieccuoi (trang_thai);

-- The partial unique index keeps the core booking rule:
-- one active wedding per hall + session + day, while still allowing a slot to be reused after cancellation.
create unique index ux_tieccuoi_active_slot
  on tieccuoi (sanh_id, ca_id, ngay_dai_tiec)
  where trang_thai <> 'DA_HUY';

create table ct_monan (
  id bigint generated by default as identity primary key,
  tieccuoi_id bigint not null references tieccuoi (id) on delete cascade,
  monan_id bigint not null references monan (id),
  so_luong integer not null default 1 check (so_luong > 0),
  don_gia_snapshot numeric(18, 2) not null check (don_gia_snapshot > 0),
  thanh_tien numeric(18, 2) not null check (thanh_tien >= 0),
  ghi_chu text,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint uq_ct_monan unique (tieccuoi_id, monan_id)
);

create index idx_ct_monan_tieccuoi_id on ct_monan (tieccuoi_id);

create table ct_dichvu (
  id bigint generated by default as identity primary key,
  tieccuoi_id bigint not null references tieccuoi (id) on delete cascade,
  dichvu_id bigint not null references dichvu (id),
  so_luong integer not null default 1 check (so_luong > 0),
  don_gia_snapshot numeric(18, 2) not null check (don_gia_snapshot > 0),
  thanh_tien numeric(18, 2) not null check (thanh_tien >= 0),
  ghi_chu text,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint uq_ct_dichvu unique (tieccuoi_id, dichvu_id)
);

create index idx_ct_dichvu_tieccuoi_id on ct_dichvu (tieccuoi_id);

create table phieuthutiencoc (
  id bigint generated by default as identity primary key,
  tieccuoi_id bigint not null references tieccuoi (id),
  nguoidung_id bigint references nguoidung (id),
  thoi_diem_thu timestamptz not null default current_timestamp,
  so_tien numeric(18, 2) not null check (so_tien > 0),
  phuong_thuc_thanh_toan varchar(20) not null default 'TIEN_MAT' check (
    phuong_thuc_thanh_toan in ('TIEN_MAT', 'CHUYEN_KHOAN', 'THE')
  ),
  ghi_chu text,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint uq_phieuthutiencoc_tieccuoi unique (tieccuoi_id)
);

create index idx_phieuthutiencoc_nguoidung_id on phieuthutiencoc (nguoidung_id);

create table phieuphatsinh (
  id bigint generated by default as identity primary key,
  tieccuoi_id bigint not null references tieccuoi (id),
  nguoidung_id bigint references nguoidung (id),
  thoi_diem_lap timestamptz not null default current_timestamp,
  tong_tien numeric(18, 2) not null default 0 check (tong_tien >= 0),
  ghi_chu text,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp
);

create index idx_phieuphatsinh_tieccuoi_id on phieuphatsinh (tieccuoi_id);
create index idx_phieuphatsinh_nguoidung_id on phieuphatsinh (nguoidung_id);

create table ct_phatsinh (
  id bigint generated by default as identity primary key,
  phieuphatsinh_id bigint not null references phieuphatsinh (id) on delete cascade,
  dichvu_id bigint not null references dichvu (id),
  so_luong integer not null check (so_luong > 0),
  don_gia_ap_dung numeric(18, 2) not null check (don_gia_ap_dung > 0),
  thanh_tien numeric(18, 2) not null check (thanh_tien >= 0),
  ghi_chu text,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint uq_ct_phatsinh unique (phieuphatsinh_id, dichvu_id)
);

create index idx_ct_phatsinh_phieuphatsinh_id on ct_phatsinh (phieuphatsinh_id);

create table hoadon (
  id bigint generated by default as identity primary key,
  tieccuoi_id bigint not null references tieccuoi (id),
  nguoidung_id bigint references nguoidung (id),
  thoi_diem_thanh_toan timestamptz not null default current_timestamp,
  tong_tien_ban numeric(18, 2) not null default 0 check (tong_tien_ban >= 0),
  tong_tien_mon_an numeric(18, 2) not null default 0 check (tong_tien_mon_an >= 0),
  tong_tien_dich_vu numeric(18, 2) not null default 0 check (tong_tien_dich_vu >= 0),
  tong_tien_phat_sinh numeric(18, 2) not null default 0 check (tong_tien_phat_sinh >= 0),
  tien_dat_coc numeric(18, 2) not null default 0 check (tien_dat_coc >= 0),
  tien_phat_tre numeric(18, 2) not null default 0 check (tien_phat_tre >= 0),
  tong_thanh_toan numeric(18, 2) not null check (tong_thanh_toan >= 0),
  ghi_chu text,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint uq_hoadon_tieccuoi unique (tieccuoi_id)
);

create index idx_hoadon_nguoidung_id on hoadon (nguoidung_id);

create table phieuhuy (
  id bigint generated by default as identity primary key,
  tieccuoi_id bigint not null references tieccuoi (id),
  nguoidung_id bigint references nguoidung (id),
  thoi_diem_huy timestamptz not null default current_timestamp,
  so_ngay_truoc_tiec integer not null check (so_ngay_truoc_tiec >= 0),
  ti_le_hoan_coc_ap_dung numeric(5, 2) not null check (
    ti_le_hoan_coc_ap_dung >= 0 and ti_le_hoan_coc_ap_dung <= 100
  ),
  tien_hoan numeric(18, 2) not null default 0 check (tien_hoan >= 0),
  ly_do text,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint uq_phieuhuy_tieccuoi unique (tieccuoi_id)
);

create index idx_phieuhuy_nguoidung_id on phieuhuy (nguoidung_id);

create table baocaodoanhso (
  id bigint generated by default as identity primary key,
  thang integer not null check (thang between 1 and 12),
  nam integer not null check (nam between 2000 and 2100),
  tong_doanh_thu numeric(18, 2) not null default 0 check (tong_doanh_thu >= 0),
  tong_so_tiec integer not null default 0 check (tong_so_tiec >= 0),
  thoi_diem_tao timestamptz not null default current_timestamp,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint uq_baocaodoanhso_thang_nam unique (thang, nam)
);

create table ct_baocaods (
  id bigint generated by default as identity primary key,
  baocaodoanhso_id bigint not null references baocaodoanhso (id) on delete cascade,
  ngay_bao_cao date not null,
  so_luong_tiec integer not null default 0 check (so_luong_tiec >= 0),
  doanh_thu numeric(18, 2) not null default 0 check (doanh_thu >= 0),
  ti_le numeric(7, 4) not null default 0 check (ti_le >= 0 and ti_le <= 100),
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint uq_ct_baocaods unique (baocaodoanhso_id, ngay_bao_cao)
);

create index idx_ct_baocaods_baocaodoanhso_id on ct_baocaods (baocaodoanhso_id);
